Repository Beramos/DS-Julia2925, pull requests merged in 2021-01, with the labels that each got.

#41 Update launch.jl
  launch.jl
Labels: bug

#47 Fixing the annoying default values for the Question block
  src/grading.jl
  src/question.jl
Labels: enhancement

#42 Intermezzo DifferentialEquations.jl and Optim
  notebooks/Project.toml
  notebooks/day2/intermezzo-diffeq-optim.jl
Labels: enhancement

#58 move DiffEq and Optim to separate environment
  notebooks/Project.toml
  notebooks/day2/intermezzo-diffeq-optim.jl
Labels: enhancement

#59 Add the `@terminal` macro
  Project.toml
  notebooks/Project.toml
  notebooks/day1/01-basics.jl
  src/DSJulia.jl
Labels: enhancement

#54 metaprogramming
  notebooks/Project.toml
  notebooks/day2/metaprogramming.jl
Labels: day 2
